# Generated by Django 3.2.13 on 2022-05-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('urun_fiyat', models.BigIntegerField()),
                ('uretim_yili', models.BigIntegerField()),
                ('kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anasayfa.kategori')),
            ],
        ),
    ]
