# Generated by Django 3.2.13 on 2022-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun_gorseli',
            field=models.FileField(blank=True, null=True, upload_to='urunresim/', verbose_name='Ürün Resimleri'),
        ),
    ]
