# Generated by Django 3.2.13 on 2022-05-20 18:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_urun_urun_gorseli'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
